# Generated by Django 4.2.15 on 2024-09-01 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Receita Tipo Imposto',
                'verbose_name_plural': 'Receita Tipos Impostos',
                'db_table': 'receita_imposto_tipo',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Receita Tipo',
                'verbose_name_plural': 'Receita Tipos',
                'db_table': 'receita_tipo',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nfe', models.CharField(max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantidade', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receita_venda_set', to='cadastros.grupoproduto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receita_venda_set', to='cadastros.vendedor')),
            ],
            options={
                'verbose_name': 'Receita Venda',
                'verbose_name_plural': 'Receita Vendas',
                'db_table': 'receita_venda',
            },
        ),
        migrations.CreateModel(
            name='Consolidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantidade', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receita_consolidacao_set', to='cadastros.produto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receita_consolidacao_set', to='receita.tipo')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receita_consolidacao_set', to='cadastros.vendedor')),
            ],
            options={
                'verbose_name': 'Receita Consolidação',
                'verbose_name_plural': 'Consolidação de Receita',
                'db_table': 'receita_consolidacao',
            },
        ),
    ]
