# Generated by Django 3.2 on 2024-09-03 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_vendedor_codigo'),
        ('receita', '0002_imposto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receita_venda_set', to='cadastros.produto'),
        ),
    ]
