# Generated by Django 4.2.16 on 2024-09-07 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0005_tipo_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidacao',
            name='imposto_tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='receita_consolidacao_set', to='receita.impostotipo'),
            preserve_default=False,
        ),
    ]
