# Generated by Django 4.2.16 on 2024-09-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0006_consolidacao_imposto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidacao',
            name='quantidade',
        ),
    ]
