# Generated by Django 4.2.16 on 2024-09-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0007_remove_consolidacao_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consolidacao',
            name='imposto_tipo',
        ),
    ]
