# Generated by Django 3.2 on 2024-10-28 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_alter_produto_managers'),
        ('receita', '0009_venda_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidacao',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receita_consolidacao_set', to='cadastros.cliente'),
            preserve_default=False,
        ),
    ]
