# Generated by Django 4.2.15 on 2024-09-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=300)),
                ('nome', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cadastros Cliente',
                'verbose_name_plural': 'Cadastros Clientes',
                'db_table': 'cadastro_cliente',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cadastros de Fornecedor',
                'verbose_name_plural': 'Cadastros de Fornecedores',
                'db_table': 'cadastro_fornecedor',
                'unique_together': {('nome', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cadastros de Grupo de Produto',
                'verbose_name_plural': 'Cadastros de Grupos de Produtos',
                'db_table': 'cadastro_grupo_produto',
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('codigo', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Cadastros de Loja',
                'verbose_name_plural': 'Cadastros de Lojas',
                'db_table': 'cadastro_loja',
            },
        ),
        migrations.CreateModel(
            name='EquipeVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadastros_equipe_venda_set', to='cadastros.loja')),
            ],
            options={
                'verbose_name': 'Cadastro Equipe de Venda',
                'verbose_name_plural': 'Cadastros Equipes de Vendas',
                'db_table': 'cadastro_equipe_venda',
                'unique_together': {('nome', 'codigo', 'loja')},
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('equipe_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadastro_vendedor_set', to='cadastros.equipevenda')),
            ],
            options={
                'verbose_name': 'Cadastro Vendedor',
                'verbose_name_plural': 'Cadastro Vendedores',
                'db_table': 'cadastro_vendedor',
                'unique_together': {('nome', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadastros_produto_set', to='cadastros.fornecedor')),
                ('grupo_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadastros_produto_set', to='cadastros.grupoproduto')),
            ],
            options={
                'verbose_name': 'Cadastros de Produto',
                'verbose_name_plural': 'Cadastros de Produtos',
                'db_table': 'cadastro_produto',
                'unique_together': {('nome', 'codigo')},
            },
        ),
    ]
