# Generated by Django 3.2 on 2024-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(default=1111, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='fornecedor',
            unique_together={('nome', 'cnpj')},
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='codigo',
        ),
    ]
