# Generated by Django 3.2 on 2024-09-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20240901_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
