# Generated by Django 3.2 on 2024-09-01 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_cliente_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipevenda',
            name='percent_comissao',
            field=models.DecimalField(decimal_places=2, default=111, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='bairro',
            field=models.CharField(default=1111, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='cep',
            field=models.CharField(default=1111, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='cidade',
            field=models.CharField(default=1111, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='cpf',
            field=models.CharField(default=11111, max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='email',
            field=models.CharField(default=1111, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='rua',
            field=models.CharField(default=11111, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loja',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='loja',
            name='uf',
            field=models.CharField(default=111, max_length=2),
            preserve_default=False,
        ),
    ]
