# Generated by Django 3.2 on 2024-09-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20240901_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='cpf',
        ),
        migrations.AddField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(default=111, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
