# Generated by Django 3.2 on 2024-09-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_produto_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
