# Generated by Django 3.2 on 2024-09-22 21:40

import django.core.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_vendedor_codigo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='produto',
            managers=[
                ('objcts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='loja',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="O número de telefone deve estar no formato '+999999999'.Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
