# Generated by Django 3.2 on 2024-09-23 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_auto_20240922_1840'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='produto',
            managers=[
            ],
        ),
    ]
